
  CREATE TABLE "USERREGISTER" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"HEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
	"AGE" NUMBER(*,0) NOT NULL ENABLE, 
	"CURRENTWEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
	"GOALWEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
	"ACTIVE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ADMIN" CHAR(1 BYTE) DEFAULT 'N', 
	 CONSTRAINT "USERREGISTER_PK" PRIMARY KEY ("ID", "IDX")
);

delete from userregister;
drop sequence userregister_idx_seq;
create sequence userregister_idx_seq;

INSERT INTO USERREGISTER (IDX, USERNAME, ID, PASSWORD, EMAIL, GENDER, HEIGHT, AGE, CURRENTWEIGHT, GOALWEIGHT, ACTIVE, STATE, ADMIN)
VALUES (1, '관리자a', 'a', '1', 'admin@example.com', '남성', 180, 30, 80, 75, '1.250', 'health', 'Y');

INSERT INTO USERREGISTER (IDX, USERNAME, ID, PASSWORD, EMAIL, GENDER, HEIGHT, AGE, CURRENTWEIGHT, GOALWEIGHT, ACTIVE, STATE, ADMIN)
VALUES (1, '관리자b', 'b', '1', 'admin@example.com', '여성', 180, 30, 80, 75, 1.725, 'health', 'Y');


  CREATE TABLE "DIET" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"DIETMEMO" VARCHAR2(2000 BYTE), 
	"DIETPICTURE" VARCHAR2(1000 BYTE) DEFAULT 'no picture', 
	"DIETWRITEDATE" VARCHAR2(20 BYTE) DEFAULT sysdate, 
	"DIETWRITETIME" VARCHAR2(20 BYTE) DEFAULT sysdate, 
	"GUP" NUMBER DEFAULT 0, 
	"ID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DIET_PK" PRIMARY KEY ("IDX")
);

delete from DIET;
drop sequence DIET_idx_seq;
create sequence DIET_idx_seq;


  CREATE TABLE "USERFOOD" 
   (	"GUP" NUMBER DEFAULT 0, 
	"FOODNAME" VARCHAR2(200 BYTE), 
	"KCAL" FLOAT(126), 
	"CARBS" FLOAT(126), 
	"PROTEIN" FLOAT(126), 
	"FAT" FLOAT(126), 
	"ID" VARCHAR2(200 BYTE), 
	"IDX" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USERFOOD_PK" PRIMARY KEY ("IDX")
);

delete from USERFOOD;
drop sequence USERFOOD_idx_seq;
create sequence USERFOOD_idx_seq;


  CREATE TABLE "FOOD" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"FOODNAME" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"KCAL" FLOAT(126) NOT NULL ENABLE, 
	"CARBS" FLOAT(126) NOT NULL ENABLE, 
	"PROTEIN" FLOAT(126) NOT NULL ENABLE, 
	"FAT" FLOAT(126) NOT NULL ENABLE, 
	 CONSTRAINT "userFOOD_PK" PRIMARY KEY ("IDX")
);

delete from FOOD;
drop sequence FOOD_idx_seq;
create sequence FOOD_idx_seq;


  CREATE TABLE "FREEBOARD" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(3000 BYTE), 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"HIT" NUMBER(*,0) DEFAULT 0, 
	"NOTICE" CHAR(3 BYTE) DEFAULT 'NO', 
	"PICTURE" VARCHAR2(2000 BYTE), 
	"COMMENTCOUNT" NUMBER(*,0) DEFAULT 0, 
	"NAME" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(100 BYTE), 
	"REALFILEPATH" VARCHAR2(2000 BYTE), 
	"SHAREDIET_GUP" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"SHARETAG" VARCHAR2(3 BYTE) DEFAULT 'NO', 
	"ADMIN" CHAR(1 BYTE), 
	 CONSTRAINT "FREEBOARD_PK" PRIMARY KEY ("IDX")
);

delete from FREEBOARD;
drop sequence FREEBOARD_idx_seq;
create sequence FREEBOARD_idx_seq;



  CREATE TABLE "FREEBOARDCOMMENT" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" CHAR(20 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"GUP" VARCHAR2(20 BYTE), 
	 CONSTRAINT "FREEBOARDCOMMENT_PK" PRIMARY KEY ("IDX")
);

delete from FREEBOARDCOMMENT;
drop sequence FREEBOARDCOMMENT_idx_seq;
create sequence FREEBOARDCOMMENT_idx_seq;


  CREATE TABLE "SHAREDIET" 
   (	"IDX" NUMBER NOT NULL ENABLE, 
	"FOODNAME" VARCHAR2(2000 BYTE), 
	"KCAL" FLOAT(20), 
	"CARBS" FLOAT(20), 
	"PROTEIN" FLOAT(20), 
	"FAT" FLOAT(20), 
	"DIETDATE" VARCHAR2(200 BYTE), 
	"DIETTIME" VARCHAR2(200 BYTE), 
	"GUP" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SHAREDIET_PK" PRIMARY KEY ("IDX")
);

delete from SHAREDIET;
drop sequence SHAREDIET_idx_seq;
create sequence SHAREDIET_idx_seq;