
  CREATE TABLE "FREEBOARDCOMMENT" 
   (   "IDX" NUMBER(*,0) NOT NULL ENABLE, 
   "GUP" NUMBER(*,0), 
   "NAME" CHAR(20 BYTE) NOT NULL ENABLE, 
   "CONTENT" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
   "WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
   "ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    CONSTRAINT "FREEBOARDCOMMENT_PK" PRIMARY KEY ("IDX")
  );
  
    CREATE TABLE "FREEBOARD" 
   (   "IDX" NUMBER(*,0) NOT NULL ENABLE, 
   "SUBJECT" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
   "CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
   "WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
   "HIT" NUMBER(*,0) DEFAULT 0, 
   "NOTICE" CHAR(3 BYTE) DEFAULT 'NO', 
   "PICTURE" CHAR(15 BYTE) DEFAULT 'no picture', 
   "COMMENTCOUNT" NUMBER(*,0) DEFAULT 0, 
   "NAME" VARCHAR2(20 BYTE), 
   "ID" VARCHAR2(100 BYTE), 
   "REALFILEPATH" VARCHAR2(2000 BYTE), 
    CONSTRAINT "FREEBOARD_PK" PRIMARY KEY ("IDX")
 );
  
    CREATE TABLE "USERREGISTER" 
   (   "IDX" NUMBER(*,0) NOT NULL ENABLE, 
   "USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
   "PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "EMAIL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "GENDER" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
   "HEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
   "AGE" NUMBER(*,0) NOT NULL ENABLE, 
   "CURRENTWEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
   "GOALWEIGHT" NUMBER(*,0) NOT NULL ENABLE, 
   "ACTIVE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
   "STATE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    CONSTRAINT "USERINFO_PK" PRIMARY KEY ("IDX")
 );
  
    CREATE TABLE "DIET" 
   (   "IDX" NUMBER(*,0) NOT NULL ENABLE, 
   "DIETMEMO" VARCHAR2(2000 BYTE), 
   "DIETPICTURE" VARCHAR2(1000 BYTE) DEFAULT 'no picture', 
   "DIETWRITEDATE" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL ENABLE, 
   "DIETWRITETIME" VARCHAR2(20 BYTE) DEFAULT sysdate NOT NULL ENABLE, 
   "ID" VARCHAR2(100 BYTE),
    CONSTRAINT "DIET_PK" PRIMARY KEY ("IDX")
  );
delete from DIET;
drop sequence DIET_idx_seq;
create sequence DIET_idx_seq;
  
  CREATE TABLE "USERFOOD" 
   (   "GUP" NUMBER DEFAULT 0 , 
   "FOODNAME" VARCHAR2(200 BYTE), 
   "KCAL" FLOAT(126), 
   "CARBS" FLOAT(126), 
   "PROTEIN" FLOAT(126), 
   "FAT" FLOAT(126), 
   "ID" VARCHAR2(200 BYTE) , 
   "IDX" NUMBER NOT NULL ENABLE, 
    CONSTRAINT "USERFOOD_PK" PRIMARY KEY ("IDX")
  );

delete from USERFOOD;
drop sequence USERFOOD_idx_seq;
create sequence USERFOOD_idx_seq;


delete from diet;
delete from userfood;
commit;
select * from diet;
select * from userfood;

    CREATE TABLE "FOOD" 
   (   "IDX" NUMBER(*,0) NOT NULL ENABLE, 
   "FOODNAME" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
   "KCAL" FLOAT(126) NOT NULL ENABLE, 
   "CARBS" FLOAT(126) NOT NULL ENABLE, 
   "PROTEIN" FLOAT(126) NOT NULL ENABLE, 
   "FAT" FLOAT(126) NOT NULL ENABLE, 
    CONSTRAINT "userFOOD_PK" PRIMARY KEY ("IDX")
 );